### ISSUE TITLE
Public roadmap?

### ISSUE THREAD

**Issue by rglastra** [vmware/mangle#44]
In reading the [other issue](https://github.com/vmware/mangle/issues/42), @aswathy-ramabhadran mentioned a January 2021 release.
This got me thinking that it would be nice if the Mangle roadmap was published (i.e. in GitHub) where we could all access it.

Is this something that we could consider doing?

And related to this, do you see any other opportunities for us to stay in lockstep with each other? I cannot find any recent commits on the repo, so I'm assuming that work is being done elsewhere?

**Comment by aswathy-ramabhadran** [comment]
@rglastra you are right. There is an internal repo of mangle that we push to regularly before the sync happens to the public repo once every release. Your ask is valid. Let me see if we can put a doc page that answers the road map question so that the community is aware of what comes up next and the tentative timelines for it.

**Comment by rglastra** [comment]
Hi @aswathy-ramabhadran, happy new year!
I'm curious if you've had a chance to think about this? Perhaps [Projects](https://github.com/vmware/mangle/projects/1) could suffice?

**Comment by aswathy-ramabhadran** [comment]
@rglastra for now I have created an [issue ](https://github.com/vmware/mangle/issues/49) that lists all the new features and have added it to the Projects section. For future release we will break it down and track it as individual issues so that the community can  provide feedback.
